owner: xnaas
repo: rimgo-instances

sites:
  - name: i.bcow.xyz
    url: https://i.bcow.xyz
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/ca.png
  - name: rimgo.pussthecat.org
    url: https://rimgo.pussthecat.org
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: img.riverside.rocks
    url: https://img.riverside.rocks
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: rimgo.totaldarkness.net
    url: https://rimgo.totaldarkness.net
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/ca.png
  - name: rimgo.bus-hit.me
    url: https://rimgo.bus-hit.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/ca.png
  - name: rimgo.esmailelbob.xyz
    url: https://rimgo.esmailelbob.xyz
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/ca.png
  - name: rimgo.lunar.icu
    url: https://rimgo.lunar.icu
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: i.actionsack.com
    url: https://i.actionsack.com
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png

status-website:
  baseUrl: /rimgo-instances
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: rimgo instances
  introTitle: "rimgo instances uptime"
  introMessage: This status page monitors [rimgo instances](https://codeberg.org/video-prize-ranch/rimgo/src/branch/main/README.md#clearnet) for uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
